# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
  - container: terraform
    image: sam123ben/terraform-pipeline:latest  # container image name
    env: 
      TF_VAR_subscription_id: $(TF_VAR_subscription_id)
      TF_VAR_tenant_id: $(TF_VAR_tenant_id)
      TF_VAR_client_secret: $(TF_VAR_client_secret)
      TF_VAR_client_id: $(TF_VAR_client_id)

steps:

- script: export TF_VAR_client_secret=$(TF_VAR_client_secret) && export TF_VAR_tenant_id=$(TF_VAR_tenant_id) && export TF_VAR_client_id=$(TF_VAR_client_id) && export TF_VAR_subscription_id=$(TF_VAR_subscription_id) && cd ./azure/example1 && terraform init && terraform plan && terraform apply -auto-approve
  displayName: 'Run the Azure resources'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
